[package]
edition = "2021"
name = "battle_bots"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

battle_bots_engine = {git = "https://github.com/holochain-immersive/battle-bots-engine", branch = "main"}
